### ISSUE TITLE
"Clown Vomit" mode has no color for "OFFLINE"

### ISSUE THREAD

**Issue by yamikuronue** [SockDrawer/SockSite#12]
"Clown Vomit" CSS lacks a color template for "TD.OFFLINE"  because I forgot it exists.

**Comment by Onyx47** [comment]
It's missing in the main.css file as well. Was that in there from the start @AccaliaDeElementia ? I don't remember seeing it when I first wrote it that bit.

**Comment by AccaliaDeElementia** [comment]
it's generated from the status messages:

Currently it can be:
- UNKNOWN
- GREAT
- GOOD (at the moment not this one, but probably soon)
- OK
- BAD
- OFFLINE

https://github.com/AccaliaDeElementia/SockSite/blob/master/config.json#L18-L24

**Comment by Onyx47** [comment]
Well, either I was blind or you added stuff.

In any case, I need to figure out a better colour scheme at this point so we can present all of them unambiguously in the table.

@yamikuronue we should probably coordinate on this so that "clown vomit" doesn't clash with status colours. We want to keep things readable in any mode.

**Comment by AccaliaDeElementia** [comment]
probably the latter.... i almost certainly added it.

my bad.

**Comment by yamikuronue** [comment]
It has a separate stylesheet, which overrides the normal one, so you can change the `color` there alongside the background in order to prevent clashes
